import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/NavBar/page"
import Footer from "@/app/components/Footer/page"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LofiTune Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="{inter.className} bg-[#041B2D] text-[white]">
        <NavBar />
        {children}
      </body>      
        <Footer />
    </html>
  );
}
